### ISSUE TITLE
Update yt-dlp as well? Or switch entirely to only keeping yt-dlp updated?

### ISSUE THREAD

**Issue by Pentaphon** [shinchiro/mpv-winbuild-cmake#152]
The youtube-dl situation seems to be getting more hopeless by the month. Perhaps it's time to move to yt-dlp?

**Comment by garoto** [comment]
Wrong repo shill.

**Comment by shinchiro** [comment]
Still not dead from my view

**Comment by Elabajaba** [comment]
Bumping this.

youtube-dl no longer has any active maintainers as dstftw has now removed themselves from the active maintainers list, and last remaining maintainer hasn't really been active since March. youtube-dl also hasn't been usable for youtube for months now, as Google throttles it to where it is essentially unusable.
