### ISSUE TITLE
mpv-x86_64-20220206-git-0197729.7z broken on Windows 7?

### ISSUE THREAD

**Issue by BrianG61UK** [shinchiro/mpv-winbuild-cmake#177]
I'm running MPV on two different 64 bit Windows 7 PCs.
I just updated to mpv-x86_64-20220206-git-0197729.7z from mpv-x86_64-20220116-git-1ba0547.7z and it seems broken.
No video playback, just a white screen. Audio plays okay.
Starts up with a white window too, no message to drag and drop files to play them.

**Comment by shinchiro** [comment]
Works on my win10. Try run without config, `mpv --no-config`

**Comment by BrianG61UK** [comment]
No difference.
(The only thing in my `mpv.conf` was `hwdec=auto`)

**Comment by shinchiro** [comment]
Try this
[mpv-x86_64-20220208-git-0197729.zip](https://github.com/shinchiro/mpv-winbuild-cmake/files/8024346/mpv-x86_64-20220208-git-0197729.zip)

**Comment by BrianG61UK** [comment]
> Try this [mpv-x86_64-20220208-git-0197729.zip](https://github.com/shinchiro/mpv-winbuild-cmake/files/8024346/mpv-x86_64-20220208-git-0197729.zip)

Unfortunately that seems no better.

**Comment by BrianG61UK** [comment]
Over on the CCCP IRC channel JEEB said:
> BrianG61UK: apparently the addition of the UNORDERED_ACCESS flag causes that with intel (on Win7). are you on intel?

I am on Intel on both the PCs.

I must admit I don't know what the UNORDERED_ACCESS flag is or who/what sets it where.

I will also add that I'd be disappointed, but I would understand and accept if you decide to drop support for Windows 7.

**Comment by avih** [comment]
Should probably be fixed by this https://github.com/mpv-player/mpv/pull/9851

Until it's fixed, adding this config should workaround the issue: `--d3d11-flip=no`.

**Comment by BrianG61UK** [comment]
Yes `--d3d11-flip=no` fixes it.
Thank you very much for your help and for your mpv binaries.

**Comment by BrianG61UK** [comment]
Nothing seems to work on Windows 7 now.

**Comment by garoto** [comment]
> Nothing seems to work on Windows 7 now.

It's all part of the `planned obsolescence` ploy by these very large `tech` conglomerates who dictate how all this shit should behave by making their payroll `FOSS` programmers to commit useless features to projects they have commit access so all the cartel can profit from it.

e.g. Vulkan shit stopped working for me with mpv about a ~year ago[0] because (and this is a guess, since there's no useful error msg whatsoever) I'm running Windows 8.1 and a 970 legacy nVidia GPU.

This whole `industry` is a joke from top to bottom.

ffmpeg and libplacebo are to blame. No wonder wm4 quit once haasn started pushing his shenanigans rendering library some 4yrs ago.
