### ISSUE TITLE
Shinchiro VS lachs0r

### ISSUE THREAD

**Issue by Chaython** [shinchiro/mpv-winbuild-cmake#25]
What's different between these branches?

**Comment by shinchiro** [comment]
My builds is constantly build every week or so with latest changes from git for mpv and all dependencies like ffmpeg, libass, freetype2 and so on

**Comment by Vangelis66** [comment]
For me, @shinchiro's builds have two main advantages: 

**1**. They don't use `schannel.dll + bcrypt.dll` native Windows libs, thus they are **still** compatible with older OSes like Vista SP2 👍 
**2**.  They come, since the start of 2018, with support for VapourSynth filters:  

https://github.com/shinchiro/mpv-winbuild-cmake/issues/1#issue-341328265

Support has been implemented in a dynamic fashion, meaning one can launch `mpv.exe` without the presence of VS .dlls (in the case one does not need the VS support...) 👍 

Many, many thanks to @shinchiro for these features 🥇
