### ISSUE TITLE
Problem when installing

### ISSUE THREAD

**Issue by primalIns** [shinchiro/mpv-winbuild-cmake#290]
hello
i downloaded mpv and when i  am installing an error like this in the cmd window says 
Error in command: reg add "HKLM\SOFTWARE\Classes\.vob\OpenWithProgIds" /v "io.mpv.vob" /f
what seems to be the problem and how to solve.
thx

**Comment by adlerzei** [comment]
I don't think this is the right place to ask for help with mpv setup issues, since this is "just" the build chain. You may get more information from the mpv community: https://mpv.io/community/. 

However, you need to provide more information about your system and perhaps a full error log if you expect help.

**Comment by zhongfly** [comment]
https://github.com/shinchiro/mpv-packaging
Shinchiro's builds use mpv-install.bat in this repo.
The bat maybe incompatible with win11.

**Comment by shinchiro** [comment]
Not sure what's problem. The install.bat only tested up to windows 10
