### ISSUE TITLE
amf-headers use git instead of svn

### ISSUE THREAD

**Issue by zhongfly** [shinchiro/mpv-winbuild-cmake#316]
Github plans to stop supporting svn after a year, so we should consider changing the amf-headers package to use git.

https://github.blog/2023-01-20-sunsetting-subversion-support/

**Comment by rorgoroth** [comment]
I ended up moving the amf-headers to git to avoid the svn dep a long time ago, the problem is (and the reason svn was used, I'm assuming) is because their repo is very bad and full of crap that isn't needed. I'm not sure if git can pull just a certain directory only so the actual files needed may need to be mirrored separately which is what I ended up doing each time a release is made.

**Comment by zhongfly** [comment]
> pull just a certain directory only

maybe [sparse checkout](https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/), [sparse index](https://github.blog/2021-11-10-make-your-monorepo-feel-small-with-gits-sparse-index/), and [partial clone](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/) can help

**Comment by shinchiro** [comment]
Alternatively, you can mirror the repo to gitlab and download the needed directory only
