### ISSUE TITLE
Is vapoursynth supported?

### ISSUE THREAD

**Issue by zc62** [shinchiro/mpv-winbuild-cmake#50]
I see that there is vapoursynth in the package list, however, it seems that the sourceforge build generated by this tool is not compiled with vapoursynth support. Is this tool unable to provide proper vapoursynth support or are there reasons not doing so? I guess because of the python issue? mpv-player/mpv#2580

[SVP](https://www.svp-team.com/wiki/SVP:mpv) has their builds with vapoursynth support. They say
>Since developer's web site doesn't provide Vapoursynth-enabled Windows version you have to use our custom build of mpv.exe and/or mpv-1.dll. 

I see a lot of files in the folder. Are they necessary if mpv is built by this tool?
![svp](https://user-images.githubusercontent.com/17048823/34380152-61663db8-eacd-11e7-980a-f3a8e7e41296.png)

**Comment by shinchiro** [comment]
Yeah, it doesn't have vapoursynth support since it depends on python. Cross-compile python on mingw is next to impossible. The only choice is make mpv support dynamic loading vapoursynth which already requested: https://github.com/mpv-player/mpv/issues/3208

**Comment by shinchiro** [comment]
Almost forgot. I've experimenting cross-compile python lately in this branch: https://github.com/shinchiro/mpv-winbuild-cmake/tree/static-python. So far it managed to compile a static library (with error). Since I'm not familiar with vapoursynth, I dont know whether a library is enough for it to work

**Comment by DeadSix27** [comment]
@shinchiro Is using dlltool and gendef an option for you? I use that to link to vapoursynth in my builds (since i also don't feel like cross compiling python), see: https://github.com/DeadSix27/vapoursynth_mingw_libs

**Comment by shinchiro** [comment]
Well, that also works but I guess it still require user to have existing python in their system for vapoursynth to works

**Comment by zc62** [comment]
@shinchiro @DeadSix27 What do I need to do to make mpv + vapoursynth work if I simply provide all the vapoursynth and python files needed in the folder where mpv.exe locates, just like what the SVP team did?

**Comment by DeadSix27** [comment]
@shinchiro while true, a python 2+ installation is probably standard on most distros these days.

**Comment by shinchiro** [comment]
@zc62 I'm testing compiling mpv with vapoursynth support. Try this:
[mpv-64bit.zip](https://github.com/shinchiro/mpv-winbuild-cmake/files/1591340/mpv-64bit.zip)

You need to do extra works to setup vapoursynth properly. Tell me if it actually works or not

**Comment by shinchiro** [comment]
nice if it works. I'll include vapoursynth support in future builds

**Comment by starks** [comment]
It works.

> Opening video filter: [vapoursynth file=C:\Users\****\AppData\Roaming\SVP4\scripts\b302708.py buffered-frames=4 concurrent-frames=15]

**Comment by DeadSix27** [comment]
@shinchiro Did you figure out how to properly cross compile python then?

**Comment by shinchiro** [comment]
Not really

**Comment by Vangelis66** [comment]
Happy New Year 2018! 
Starting by thanking again @shinchiro for restoring Windows Vista SP2 support in his recent builds, I want to confirm the implementation of VapourSynth support (**mpv-i686-20171229-git-d9ca235** and later) did not break things for Vista, so all in all a stupendous enhancement! :1st_place_medal:
Both aforementioned build (which does have a hard dependency on `VapourSynth.dll + VSScript.dll` (and, at least on my setup, `msvcp140.dll + vcruntime140.dll`) as well as the latest compile **mpv-i686-20180104-git-a9a4d63** (which, BTW, doesn't depend on additional VS DLLs) load and run fine: 
```
mpv 0.28.0-74-ga9a4d6349a Copyright ? 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Thu Jan  4 21:10:46 UTC 2018
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.3.100
   libswscale      5.0.101
   libavfilter     7.10.100
   libswresample   3.0.101
ffmpeg version: N-45916-g89bbf5c7ec
```
However, I want to report a peculiar glitch since VS support was introduced; I mostly use the mpv compiles inside the SMPlayer Windows frontend; with the last non-VS build (**mpv-i686-20171224-git-a721dac**), 
`Help => About SMPlayer => Info` tab _correctly picks up mpv's version string_, please see: 

![mpv](https://user-images.githubusercontent.com/9669492/34683509-ef4154ba-f4aa-11e7-9e93-f39fe5273702.jpg)

On the contrary, with the VS enabled versions of mpv, that version string is not picked up/reported by the SMPlayer GUI; e.g., with `mpv-0.28.0-74-git-20180104-ga9a4d63` I get: 

![mpv vs](https://user-images.githubusercontent.com/9669492/34683716-8ff8a9a8-f4ab-11e7-80cf-1847fd74a259.jpg)

Obviously, this is a mildly important issue which doesn't affect in any other way the functions of @shinchiro compiled mpv builds inside SMPlayer; before I take this with the SMPlayer dev, do you feel that something in the way the VS enabled compilation was realised is the cause of this? 
Thank you in advance for any troubleshooting 👍 

One final, rather pedantic, query: 

`ffmpeg version: N-45916-g89bbf5c7ec`

How to you actually calculate the N-tag value there? Most FFmpeg builds I find on-line are in the 8xxxx range (?). At first I thought you were using some custom older fork, but commit `89bbf5c7ec` is actually a recent one in the master FFmpeg branch (https://github.com/FFmpeg/FFmpeg/commit/89bbf5c7ec). 
I have cloned the FFmpeg repo locally, but 
```sh
$ git reset --hard 89bbf5c7ec
fatal: ambiguous argument '89bbf5c7ec': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
Thus, I am unable to issue `$ git describe --abbrev=7 --tags --match N`
 Any more info on this will be highly appreciated...

Kindest regards

**Comment by shinchiro** [comment]
^ That's not related with vapoursynth. Recently, mpv add the trademark symbol '©' in version line's version, which might break with how SMplayer parse/read the version's info. Tell the SMplayer's dev

>How do you actually calculate the N-tag value there? 

Well, it was set automatically by FFmpeg. About the commit's hash, the default which git generated is 7 digit. Since ffmpeg is older project with thousands commits, it makes sense to use longer commit's hash to avoid hash collision (eg. same hash)

**Comment by Vangelis66** [comment]
@shinchiro wrote: 

> ^ That's not related with vapoursynth. Recently, mpv add the trademark symbol '©' in version line's 
> version, which might break with how SMplayer parse/read the version's info. Tell the SMplayer's dev

Hello :smiley:
Apologies I initially thought the _version string_ issue I reported had something to do with VapourSynth support in mpv; it was pure coincidence! 

Since then, **SMPlayer** has been updated, now at version **18.2.0.8910**; but most likely it wasn't an SMPlayer issue to begin with; with your previous compile (**mpv-0.28.0-167-git-20180126-gf8263e8**) this small annoyance persisted: 

![lastbad](https://user-images.githubusercontent.com/9669492/35785057-1915ead6-0a26-11e8-9083-abd779704f55.jpg)

however with your most recent compile (**mpv-0.28.0-215-git-20180203-g59f9547**) this "issue" is fixed, supposedly in a commit from the mpv team themselves: 

![firstgood](https://user-images.githubusercontent.com/9669492/35785113-9439e8f2-0a26-11e8-8a12-d6ff4f346610.jpg)

So, all's well that ends well :smile: BTW, I'll never stop thanking you for providing Vista 32-bit compatible mpv Windows builds ! :heart:
