### ISSUE TITLE
CMake Error at /__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build32/packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure-.cmake:49

### ISSUE THREAD

**Issue by wbtcpip2** [shinchiro/mpv-winbuild-cmake#548]
`[806/822] Performing configure step for 'ffmpeg'
FAILED: packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure /__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build32/packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure 
cd /__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build32/packages/ffmpeg-prefix/src/ffmpeg-build && /usr/bin/cmake -P /__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build32/packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure-.cmake && /usr/bin/cmake -E touch /__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build32/packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure
CMake Error at /__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build32/packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure-.cmake:49 (message):
  Command failed: 1

   '/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build32/exec' 'CONF=1' '/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/src_packages/ffmpeg/configure' '--cross-prefix=i686-w64-mingw32-' '--prefix=/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build32/install/i686-w64-mingw32' '--arch=i686' '--target-os=mingw32' '--pkg-config-flags=--static' '--enable-cross-compile' '--enable-runtime-cpudetect' '--enable-gpl' '--enable-version3' '--enable-nonfree' '--enable-postproc' '--enable-avisynth' '--enable-vapoursynth' '--enable-libass' '--enable-libbluray' '--enable-libfreetype' '--enable-libfribidi' '--enable-libfontconfig' '--enable-libharfbuzz' '--enable-libmodplug' '--enable-libopenmpt' '--enable-libmp3lame' '--enable-lcms2' '--enable-libopus' '--enable-libsoxr' '--enable-libspeex' '--enable-libvorbis' '--enable-libbs2b' '--enable-librubberband' '--enable-libvpx' '--enable-libwebp' '--enable-libx264' '--enable-libx265' '--enable-libaom' '--enable-librav1e' '--enable-libdav1d' '--enable-libdavs2' '--enable-libuavs3d' '--enable-libxvid' '--enable-libzimg' '--enable-openssl' '--enable-libxml2' '--enable-libmysofa' '--enable-libssh' '--enable-libsrt' '--enable-libvpl' '--enable-libjxl' '--enable-libplacebo' '--enable-libshaderc' '--enable-libzvbi' '--enable-libaribcaption' '--enable-cuda-llvm' '--enable-cuvid' '--enable-nvdec' '--enable-nvenc' '--enable-amf' '--disable-doc' '--disable-ffplay' '--disable-ffprobe' '--enable-vaapi' '--disable-vdpau' '--disable-videotoolbox' '--disable-decoder=libaom_av1' '--extra-cflags='-Wno-error=int-conversion'' '--extra-libs='-lstdc++''

  See also

    /__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build32/packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure-*.log

ninja: build stopped: subcommand failed.
+ '[' -d '/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build32/mpv-i686*' ']'
+ echo 'Failed compiled 32-bit. Stop'
+ exit 1
Failed compiled 32-bit. Stop
Error: Pr`

**Comment by zhongfly** [comment]
You canl use this markdown syntax to format your content: [quoting code](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
What you posted doesn't make much sense, you should be able to see that it prompts:
```
See also '/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build32/packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure-*.log'
```
It tells that you can see the detailed reason in `packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure-*.log`,this file you can find in artifact of your action:
![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/11155705/85ebf664-d4d3-49d7-9118-89e38d2d397f)
![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/11155705/567e14a6-4c3e-42ce-bd1c-f7829e16525c)
Read this two logs, you will know the reason is:
```
ERROR: libbluray not found using pkg-config
```

So when posting an issue here you can write: you compiled 32-bit mpv with gcc and ffmpeg configure failed because `libbluray not found using pkg-config`.You can also post logs by a link : https://github.com/wbtcpip2/mpv-winbuild/actions/runs/7059522345

**Comment by wbtcpip2** [comment]
ok thank you. sorry for my bad format report. i will follow your directions next time.

**Comment by shinchiro** [comment]
This only  happen on gcc for unknown reason

**Comment by wbtcpip2** [comment]
thank you for investigating the problem, i need to use gcc builds because i have this same problem #458 and my app is 32 bits

**Comment by wbtcpip2** [comment]
ok i try and report

**Comment by shinchiro** [comment]
> #560 should fix the gcc build issue, can you try it?

Thats messy solution. I got other solution which is good enough
