### ISSUE TITLE
lua introspective facilities bug

### ISSUE THREAD

**Issue by 57op** [shinchiro/mpv-winbuild-cmake#81]
Hello,

I've been using your mpv releases along with some lua scripts.
Since recently, one of them stopped working.
The reason it doesn't work anymore it's due to the script attempting to find its own path using the function `debug.getinfo`. Basically this function return a table/map with the field `source`:

> source --- Where the function was defined. If the function was defined in a string (through loadstring), source is that string. If the function was defined in a file, source is the file name prefixed with a `@´. [0]

Since `mpv-x86_64-20200510-git-4e94b21` build, the `source` field isn't prefixed anymore with a `@` and breaks some assumptions made by some scripts which basically ignore the first character by substringing.
Removing the first character, not being a `@`, leads to file I/O errors (e.g. `Z:\path\to\script` → `:\path\to\script`).

I made a simple script to track where this bug started occurring:
```lua
local function script_path()
  return debug.getinfo(2, "S").source
end

mp.msg.info(script_path())
```

This is the output:
| mpv version | source field |
| ------------ | ------------ |
| mpv-x86_64-20200419-git-a09c769 | @bug.lua |
| mpv-x86_64-20200426-git-640db1e | @bug.lua |
| mpv-x86_64-20200510-git-4e94b21 | bug.lua |
| mpv-x86_64-20200517-git-152b0e2 | bug.lua |
| mpv-x86_64-20200614-git-c7fe4ae | bug.lua |
| mpv-x86_64-20200621-git-dc24a43 | bug.lua |

I hope this could be of help,
Thanks for your work!

[0] https://www.lua.org/pil/23.1.html

**Comment by shinchiro** [comment]
As far I know, the only difference I made to luajit on 10 May and onward is enable LUA52COMPAT. I'm not sure if that is the case

**Comment by shinchiro** [comment]
This actually mpv's bug. If you run the script with default luajit.exe interpreter, it has `@` prefix
[luajit-32bit.zip](https://github.com/shinchiro/mpv-winbuild-cmake/files/8053676/luajit-32bit.zip)

(After 2 years, I only got time to properly check this, sorry)

**Comment by 57op** [comment]
no problem at all, thanks for your time and awesome work!

**Comment by avih** [comment]
> mpv-x86_64-20200426-git-640db1e 	@bug.lua
> mpv-x86_64-20200510-git-4e94b21 	bug.lua

Between these dates mpv changed from loading it as a file to loading it as a string, because `luaL_loadfile` doesn't support unicode file names on windows, so to support that, mpv loads the file correctly into a string according to its unicode name, and then loads the string into lua.

mpv can't control which prefixes lua adds to the name when different load APIs are used, and its not mpv's job to try and emulate such prefix itself (e.g. if tomorrow lua decides to prefix content loaded as string with `#` - mpv can't override it even if it wanted to).

Either way, the cause is a change in mpv itself, and the other cause is that lua prefixes the name depending on which API was used to load the content.

Also, `debug.WHATEVER` is a debug API and is not meant for production. In part, it reflects the actual C API which was used to load the file (e.g. by prefixing `@` when `luaL_loadfile` is used, but not when `luaL_loadbuffer` is used), but an application can load a file in different ways, and mpv doesn't guarantee which API it will use for loading files.

If anything, you can request a feature to add the main loaded file as some mpv API, e.g. `mp.get_script_file()` like the JS api has, but lua currently doesn't.
